### ISSUE TITLE
Can we get a 1.18 version?

### ISSUE THREAD

**Issue by TheZennou** [YoungSoulluoS/Fresh-Animations-CEM-fork#14]
A lot of people still play 1.18 especially in mod packs. Although I see why this might not be a priority since fresh animations is usually a vanilla+ type of resourcepack, but still I'd love to see it. No hard feelings if it's possible however, you are doing this for free after all.

**Comment by marklangerhacker** [comment]
It's don't an issue

**Comment by Thanos1716** [comment]
The current 1.19 version works perfectly fine with the supported CEMs on 1.18 minecraft, just load the 1.19 pack in 1.18 with CEM for fabric (1.18 version) installed and the correct settings, and you just have to click through the "Are you sure you want to load this pack?" screen
If you want the pack not to have the red border when loading it (or if you want to load it from a server I think), all you have to do is change the `"pack_format"` attribute to `8` rather than `9` in the `pack.mcmeta` file

**Comment by SoulxluoS** [comment]
it's a fork of my fork for 1.18, not mine and not the latest version of my fork
https://github.com/pikasalt/cem/releases

**Comment by SoulxluoS** [comment]
Added my 1.18 version CEM https://github.com/YoungSoulluoS/cemFork/releases
